language: java
jdk: 
  - openjdk8

script:
  - cd NewFutureTraderBackend
  - chmod +x mvnw
  - ./mvnw clean install
  - mkdir -p dev/backend
  - cp target/new-futuretrader-backend-app.jar ../dev/backend
