language: java
jdk: 
  - openjdk8
services:
  - docker
  
script:
  - cd NewFutureTraderBackend
  - chmod +x mvnw
  - ./mvnw clean install
  - mkdir -p dev/backend
  - pwd
  - cp target/new-futuretrader-backend-app.jar dev/backend
  
after_success:
  - export DEPLOY_TIMESTAMP=`date +'%Y%m%d-%H%M%S'`
  # Creating a custom tag for the docker image in addition to the default "latest" tag.
  - docker build -t ft-backend:$DEPLOY_TIMESTAMP-$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH -t ft-backend:latest .
  - docker build -t web-frontend:$DEPLOY_TIMESTAMP-$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH -t web-frontend:latest .
  # script: pass backend-namespace
  - ./build-backendimage.sh ft-backend
  # script: pass frontend-namespace
  - ./build-frontendimage.sh web-frontend
  
  

